kafka {
    input {
        brokers: "localhost:9092"
        topic: "bgp-evelog"
        maxOffsetsPerTrigger: 4000000
        startingOffsets: "latest"
    }
}
spark {
    checkpoint: "/path/to/checkpoint"
    triggerProcessingTime: "30 seconds"
}
elasticsearch {
    url: "https://localhost:9200"
    port: "9200"
    cert: "/path/to/cert.jks"
    user: "elastic"
    password: "password"
    index: "bgp-evelog"
    elasticsearch_cert_password: "cert_password"
}
ftp {
    hostname: "ftp.example.com"
    user: "ftp_user"
    password: "ftp_password"
    paths: "/path/to/ftp/directory"
}
default_alias: ""
vlan_map_alias_url: "http://vlan_map_alias"
